### ISSUE TITLE
Various: footnote problems

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-fra#37]
The following 14 texts (found by `//hi[contains(., '*')])` need attention to their footnotes
FRA00401  
FRA01201
FRA01403
FRA02202
FRA02203
FRA02601
FRA02602
FRA02603
FRA02802
FRA03701
FRA03702
FRA03704
FRA03901
FRA03903

**Comment by christofs** [comment]
Oh. Will look into it.

**Comment by christofs** [comment]
FRA04001 -- look into as well.
