### ISSUE TITLE
Add narrative-perspective to "profileDesc/textClass/keyword/term"

### ISSUE THREAD

**Issue by christofs** [COST-ELTeC/ELTeC-fra#39]
narrative-perspective: heterodiegetic, homodiegetic, autodiegetic, epistolary

**Comment by lb42** [comment]
Using textClass/keyword/term for this is easy and requires no change to the schema. But if it's likely to be generally useful, and there is a consensus on the value list, we could also consider making such a revision, adding a new element to textDesc like so:
~~~~
<e:narrativeType key="hetero"/>
~~~~
which would enable us to control the values. Alternatively, we could think about using @ref on term to point to a predefined element in some taxonomy referenced by the @scheme attribute on keywords.

**Comment by christofs** [comment]
Good point. For the moment, I don't think there is a consensus and I am just experimenting with this feature. I've chosen narrative perspective for a start as it is relevant to the group doing the direct speech recognition. WG3 will be best positioned to recommend key categories with good consensual values.

**Comment by christofs** [comment]
Closing this as far as this repo is concerned, but the question of how to best encode this across collections is still open.
