### ISSUE TITLE
author@ref syntax

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-fra#45]
Where you want to supply codes for an author in two different authority files, pointers should be separated by white space, not semicolons. For exanple, in FRA06501_Gyp.xml:	
~~~~
<author ref="viaf:96218572;wikidata:Q199228">Gyp ... </author>
~~~~
should be 
~~~~
<author ref="viaf:96218572 wikidata:Q199228">Gyp ... </author>
~~~~
See definition for this element in the schema.

**Comment by christofs** [comment]
Thanks for noticing! Will fix that.
