### ISSUE TITLE
links to print sources

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-fra#46]
This is definitely a long term request, but I just noticed that only 8 of files contain links to their  print source page images in Gallica. I am sure others are available, and it would be nice to see their arks too, one day...

**Comment by christofs** [comment]
Thanks for checking. However, only 9 texts come from Gallica (so one 'ark' is missing). Most are from Ebooks libres et gratuits or the closely related Bibliothèque électronique du Québec (around 45 texts) and from Wikisource (10 texts). The rest are from various sources. In most of these cases, unfortunately, probably with the exception of Wikisource, no provenance information of this kind is usually provided. I'll see what can be done.

**Comment by lb42** [comment]
Just to clarify, I meant that it would be nice to include a link to a digital facsimile of the first (or early) edition where one is available online, whether or not this is the actual edition transcribed. For the same reason as we provide a date for the first edition, whether or not we are transcribing same. I have just completed this exercise for the English texts, and succeeded in tracking down all of them eventually (though not without some difficulty!)

**Comment by christofs** [comment]
Ah, I see! Well, we could place that link in "printSource" and/or in "firstEdition", as appropriate. But where do you place it in cases where the digital facsimile you found corresponds to neither?

**Comment by lb42** [comment]
Inside a separate printSource bibl if it's really different. But the idea was to find one close to either the first ed or the transcribed source.

**Comment by christofs** [comment]
Bitte durch alle Dateien gehen und folgendes prüfen: 

1. Gibt es bereits einen Link zu einem digitalen Faksimile (üblicherweise liegen die dann bei der BnF, der französischen Nationalbibliothek) entweder in ```bibl type="printSource"``` oder in ```bibl type firstEdition```?
2. Wenn nein, bitte eine solches Facsimile recherchieren, hier im Gallica-Katalog: https://gallica.bnf.fr/services/engine/search/advancedSearch/
3. Wir suchen den "ark"-Link entweder für die Ausgabe, die der "printSource" entspricht, oder wenn es da keinen Eintrag gibt oder nicht klar ist, welches die "print Source" überhaupt ist, die Ausgabe, die der "firstEdition" entspricht, oder wenn beide nicht zu finden sind, eine andere Ausgabe, die zeitlich möglichst nahe an der firstEdition liegt. 
4. Dann bitte innerhalb von ```bibl``` im Element ```ref``` mit Attribut ```target``` den kompletten Permalink eintragen, bspw. ```<ref target="https://gallica.bnf.fr/ark:/12148/bpt6k3045979q"></ref>```

Ein Beispiel, wie es korrekt ist, finden Sie in "FRA00101_Adam.xml", wenn Sie Ihr repo aktualisieren. Dort für die "firstEdition", weil ich keine Ausgabe von 1868 finden konnte, die offenbar die Grundlage für die digitale Fassung bei Wikisource ist. 

Die Angabe fehlt sehr oft, das wird also etwas Zeit in Anspruch nehmen.
